# UTS 


NAMA : Muhammad Yusuf Ibrahim

NIM : 210411100095

# Naive Bayes

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/master/dataset.csv')
dataset.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
X = dataset.iloc[:,:14].values
y = dataset['target'].values
dataset.head(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [7]:
y_pred = classifier.predict(X_test) 
y_pred

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score 
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  1.0


array([[30,  0],
       [ 0, 31]])

**Kesimpulan** : berikut prediksi "Target" menggunakan naive bayes

In [9]:
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values  Predicted Values
0             1                 1
1             1                 1
2             0                 0
3             0                 0
4             0                 0
..          ...               ...
56            1                 1
57            1                 1
58            1                 1
59            1                 1
60            1                 1

[61 rows x 2 columns]

# KNN

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [11]:
df = pd.read_csv("https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/master/dataset.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Melihat ukuran dataset

In [12]:
df.shape

(303, 14)

Membagi data ke x dan y

In [13]:
# X tanpa label
X = df.drop(columns=["target"])
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [14]:
#y labelnya saja
y = df["target"].values
y[0:303]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

Membagi data ke data test dan data training.

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0, stratify=y)

In [16]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train[:5]

array([[ 0.1762246 ,  0.63794729, -0.95894245, -0.09681599,  0.76359577,
         2.21414521, -1.02899151, -1.99995062,  1.47790748,  0.51824669,
        -2.22991675, -0.71743331,  1.09984435],
       [ 0.39834103,  0.63794729, -0.95894245, -0.21138553, -0.55045027,
        -0.45164156, -1.02899151, -0.79159882,  1.47790748,  1.04779925,
        -0.61905151,  2.17621437,  1.09984435],
       [-0.49012468, -1.56752763,  0.96690048, -0.66966368, -0.49161239,
        -0.45164156,  0.85749293,  0.37359755, -0.67663234,  0.51824669,
        -0.61905151, -0.71743331, -0.5035432 ],
       [-0.04589182,  0.63794729, -0.95894245, -1.24251137, -0.09935984,
        -0.45164156,  0.85749293, -1.00737593,  1.47790748,  1.57735181,
        -0.61905151,  0.24711592,  1.09984435],
       [-0.37906646,  0.63794729, -0.95894245,  0.4760317 ,  1.05778518,
        -0.45164156,  0.85749293, -1.17999762,  1.47790748,  2.81297445,
        -0.61905151,  2.17621437,  1.09984435]])

Membangun knn classifier

In [17]:
knn = KNeighborsClassifier(n_neighbors = 5,metric = 'minkowski', p = 2)
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
KNeighborsClassifier()

KNeighborsClassifier()

In [19]:
knn.predict(X_test)[0:14]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0])

In [20]:
#check accuracy of our model on the test data
knn.score(X_test, y_test)

0.8032786885245902

Berikut adalah hasil akurasi:

In [21]:
from sklearn.metrics import *
import numpy as np

#Check Accuracy precision, recall, f1-score
print( classification_report(y_test, knn.predict(X_test)) )
#Another way to get the models accuracy on the test data
print(F'Accuracy:',accuracy_score(y_test, knn.predict(X_test)))
print(F'Precision:', precision_score(y_test, knn.predict(X_test)))
print(F'Recall:', recall_score(y_test, knn.predict(X_test)))
print(F'F1 Score:', f1_score(y_test, knn.predict(X_test)))

#Check Roc Auc Score
print( F'Roc Auc Score:',roc_auc_score(y_test, knn.predict(X_test)) )

print( F'Balanced Accuracy Score:',balanced_accuracy_score(y_test, knn.predict(X_test)) ) 
print( F'Confusion Matrix:',confusion_matrix(y_test, knn.predict(X_test)) )
print()#Print a new line

              precision    recall  f1-score   support

           0       0.83      0.71      0.77        28
           1       0.78      0.88      0.83        33

    accuracy                           0.80        61
   macro avg       0.81      0.80      0.80        61
weighted avg       0.81      0.80      0.80        61

Accuracy: 0.8032786885245902
Precision: 0.7837837837837838
Recall: 0.8787878787878788
F1 Score: 0.8285714285714285
Roc Auc Score: 0.7965367965367965
Balanced Accuracy Score: 0.7965367965367965
Confusion Matrix: [[20  8]
 [ 4 29]]

